version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=neoeduc'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data1:/var/lib/postgresql/data1  # Volume para persistência dos dados

volumes:
  postgres_data1:  # Define o volume para armazenar os dados do banco